config/routes.rb
Rails.application.routes.draw do
  #pages routes
  get '/', to: 'pages#home', as: 'root'
  get '/about', to: 'pages#about', as: 'about'

  #dogs routes
  get '/dogs', to: 'dogs#index', as: 'dogs'
  get '/dogs/:id', to: 'dogs#show', as: 'dog'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def index
    @dogs = Dog.all
  end

  def show
    @dog = Dog.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dogs/index.html.erb
<h1>These Are the Dogs</h1>
<ul>
  <% @dogs.each do |dog| %>
    <li>
      <%= link_to(dog_path(dog), class: "orange-link") do %>
        <strong><%= dog.name %></strong> -- <span>Check it out!</span>
      <% end %>
    </li>
  <% end %>
</ul>

<!-- Link_to practice! -->
<%= link_to root_path do %>
  <%= image_tag 'helper_dog.png', class: "small-image" %>
<% end %>

<br>
<%= link_to "About", about_path, class: "orange-link", id: "green-background" %>

<!-- Social Buttons -->
<br>
<%= link_to "Facebook", "http://www.facebook.com", target: "_blank", class: "orange-link" %>
<br>

<!-- Two ways to create the same link -->
<%= link_to image_tag("twitter.png", class:"small-image"), "http://www.twitter.com", target: "_blank"%>

<%= link_to "http://www.twitter.com", target: "_blank" do %>
  <%= image_tag("twitter.png", class:"small-image") %>
<% end %>

app/views/dogs/show.html.erb
<h1>This is <%= @dog.name %>!</h1>
<%= link_to 'All Dogs', dogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelperDog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is an app to practice using rails helpers.</h1>
<%= link_to "Home", root_path %>

app/views/pages/home.html.erb
<h1>Welcome to Helper Dog</h1>
<%= link_to "About", about_path %>
<br>
<%= link_to 'All Dogs', dogs_path %>
<br>
<%= image_tag "helper_dog.png" %>